name: Build Windows Executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Wine
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y wine32 wine64

    - name: Set up Python for Wine
      run: |
        wget https://www.python.org/ftp/python/3.9.1/python-3.9.1.exe
        wine python-3.9.1.exe /quiet InstallAllUsers=1 PrependPath=1

    - name: Install dependencies using Wine
      run: |
        wine python -m pip install pyinstaller

    - name: Build Windows executable using Wine
      run: |
        wine python -m PyInstaller --onefile main.py

    - name: Upload Windows executable as artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-executable
        path: dist/main.exe  # Make sure to update the path if necessary
